naruto = Ninja.create(name: "Uzumaki Naruto", description: "A Genin from Team 7, Naruto is an orphan with the goal to one day become Hokage. Using his signature move, Shadow Clones, Naruto is able to perform powerful moves such as the Uzumaki Naruto Combo and the Rasengan.", associations: ["Genin", "Konoha", "Team 7"])
sakura = Ninja.create(name: "Haruno Sakura", description: "A Genin from Team 7, Sakura is very intelligent, but self-conscious about herself. Having just recently received training from Tsunade, Sakura is now able to deliver powerful punches and heal her own allies.", associations: ["Genin", "Konoha", "Team 7"])
sasuke = Ninja.create(name: "Uchiha Sasuke", description: "A Genin from Team 7, Sasuke is the lone survivor of the Uchiha clan and has sworn vengeance against his brother. Using his sharingan, Sasuke is able to anticipate incoming attacks and is capable of advanced offensive moves.", associations: ["Genin", "Konoha", "Team 7"])

uzumaki_naruto_combo = Skill.create(position: 1, name: "Uzumaki Naruto Combo", description: "Naruto's version of the Lion Combo. This skill deals 20 damage to one enemy. During 'Shadow Clones' this skill will deal 10 additional damage.", cooldown: 0, taijutsu_cost: 1, bloodline_cost: 0, ninjutsu_cost: 0, genjutsu_cost: 0, random_cost: 0, alternates: false, classes: ["Physical", "Meelee", "Instant"])
rasengan = Skill.create(position: 2, name: "Rasengan", description: "Naruto hits one enemy with a ball of chakra dealing 45 damage to them and stunning their skills for 1 turn. This skill requires 'Shadow Clones'.", cooldown: 1, taijutsu_cost: 0, bloodline_cost: 0, ninjutsu_cost: 1, genjutsu_cost: 0, random_cost: 1, alternates: false, classes: ["Chakra", "Meelee", "Instant"])
shadow_clones = Skill.create(position: 3, name: "Shadow Clones", description: "Naruto creates multiple shadow clones hiding his true self. Naruto gains 15 points of damage reduction for 4 turns. During this time 'Uzumaki Naruto Combo' will deal 10 additional damage and 'Rasengan' can be used.", cooldown: 3, taijutsu_cost: 0, bloodline_cost: 0, ninjutsu_cost: 0, genjutsu_cost: 0, random_cost: 1, alternates: false, classes: ["Chakra", "Instant"])
sexy_technique = Skill.create(position: 4, name: "Sexy Technique", description: "This skill makes Uzumaki Naruto invulnerable for 1 turn.", cooldown: 4, taijutsu_cost: 0, bloodline_cost: 0, ninjutsu_cost: 0, genjutsu_cost: 0, random_cost: 1, alternates: false, classes: ["Chakra", "Instant"])

ko_punch = Skill.create(position: 1, name: "KO Punch", description: "Sakura punches one enemy with all her strength dealing 20 damage to them and stunning their physical or mental skills for 1 turn. During 'Inner Sakura', KO Punch deals 10 additional damage.", cooldown: 0, taijutsu_cost: 1, bloodline_cost: 0, ninjutsu_cost: 0, genjutsu_cost: 0, random_cost: 0, alternates: false, classes: ["Physical", "Meelee", "Instant"])
mystical_palm_healing = Skill.create(position: 2, name: "Mystical Palm Healing", description: "Using basic healing techniques Sakura heals herself or one ally for 25 health.", cooldown: 0, taijutsu_cost: 0, bloodline_cost: 0, ninjutsu_cost: 1, genjutsu_cost: 0, random_cost: 0, alternates: false, classes: ["Chakra", "Instant"])
inner_sakura = Skill.create(position: 3, name: "Inner Sakura", description: "Sakura's inner self surfaces and urges her on. For 4 turns, Sakura will gain 10 points of damage reduction and will ignore all non-damage effects other than chakra cost changes. During this time 'KO Punch' will deal 10 additional damage.", cooldown: 4, taijutsu_cost: 0, bloodline_cost: 0, ninjutsu_cost: 0, genjutsu_cost: 0, random_cost: 1, alternates: false, classes: ["Mental", "Unique", "Instant"])
sakura_replacement_technique = Skill.create(position: 4, name: "Sakura Replacement Technique", description: "This skill makes Haruno Sakura invulnerable for 1 turn.", cooldown: 4, taijutsu_cost: 0, bloodline_cost: 0, ninjutsu_cost: 0, genjutsu_cost: 0, random_cost: 1, alternates: false, classes: ["Chakra", "Instant"])

lion_combo = Skill.create(position: 1, name: "Lion Combo", description: "Copying a taijutsu combo that Lee used on him, Sasuke deals 30 damage to one enemy. This skill will deal an additional 15 damage to an enemy affected by 'Sharingan'.", cooldown: 0, taijutsu_cost: 1, bloodline_cost: 0, ninjutsu_cost: 0, genjutsu_cost: 0, random_cost: 1, alternates: false, classes: ["Physical", "Meelee", "Instant"])
chidori = Skill.create(position: 2, name: "Chidori", description: "Using a lightning element attack jutsu, Sasuke deals 30 piercing damage to one enemy. This skill will deal an additional 25 damage to an enemy affected by 'Sharingan'.", cooldown: 1, taijutsu_cost: 0, bloodline_cost: 0, ninjutsu_cost: 1, genjutsu_cost: 0, random_cost: 1, alternates: false, classes: ["Chakra", "Meelee", "Instant"])
sharingan = Skill.create(position: 3, name: "Sharingan", description: "Sasuke targets one enemy. For 4 turns, Sasuke will gain 15 points of damage reduction. During this time, that enemy will be unable to reduce damage or become invulnerable.* This will end if Sasuke dies.", cooldown: 4, taijutsu_cost: 0, bloodline_cost: 0, ninjutsu_cost: 0, genjutsu_cost: 0, random_cost: 1, alternates: false, classes: ["Meelee", "Unique", "Ranged", "Instant"])
swift_block = Skill.create(position: 4, name: "Swift Block", description: "This skill makes Uchiha Sasuke invulnerable for 1 turn.", cooldown: 4, taijutsu_cost: 0, bloodline_cost: 0, ninjutsu_cost: 0, genjutsu_cost: 0, random_cost: 1, alternates: false, classes: ["Physical", "Instant"])

naruto.skills << uzumaki_naruto_combo << rasengan << shadow_clones << sexy_technique
sakura.skills << ko_punch << mystical_palm_healing << inner_sakura << sakura_replacement_technique
sasuke.skills << lion_combo << chidori << sharingan << swift_block